services:
  - type: web
    name: ispch-search
    runtime: python
    plan: free
    buildCommand: "pip install -r requirements.txt && python manage.py collectstatic --noinput"
    startCommand: "python manage.py migrate && gunicorn ispch_project.wsgi:application"
    envVars:
      - key: DEBUG
        value: "False"
      - key: DJANGO_SECRET_KEY
        generateValue: true        
      - key: PG_DB
        value: postgres
      - key: PG_USER
        sync: false
      - key: PG_PASSWORD
        sync: false
      - key: PG_HOST
        sync: false
      - key: PG_PORT
        value: "5432"
      - key: RENDER_EXTERNAL_HOSTNAME
        sync: false