# Generated by Django 6.0.6 on 2026-06-17 06:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registro', models.CharField(max_length=30, unique=True)),
                ('nombre', models.CharField(max_length=255)),
                ('ref_tramite', models.CharField(blank=True, max_length=50)),
                ('equivalencia', models.CharField(blank=True, max_length=100)),
                ('titular', models.CharField(blank=True, max_length=255)),
                ('estado', models.CharField(blank=True, max_length=30)),
                ('resolucion', models.CharField(blank=True, max_length=20)),
                ('fecha_inscripcion', models.DateField(blank=True, null=True)),
                ('ultima_renovacion', models.DateField(blank=True, null=True)),
                ('prox_renovacion', models.DateField(blank=True, null=True)),
                ('regimen', models.CharField(blank=True, max_length=100)),
                ('via_administracion', models.CharField(blank=True, max_length=100)),
                ('condicion_venta', models.CharField(blank=True, max_length=100)),
                ('farmacovigilancia', models.CharField(blank=True, max_length=255)),
                ('indicacion', models.TextField(blank=True)),
                ('source_url', models.URLField(blank=True, max_length=300)),
                ('scraped_at', models.DateTimeField(blank=True, null=True)),
                ('raw_html', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_envase', models.CharField(blank=True, max_length=100)),
                ('descripcion', models.CharField(blank=True, max_length=500)),
                ('periodo_eficacia', models.CharField(blank=True, max_length=50)),
                ('condicion_almacenamiento', models.CharField(blank=True, max_length=255)),
                ('contenido', models.CharField(blank=True, max_length=100)),
                ('unidad_medida', models.CharField(blank=True, max_length=50)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packagings', to='registros.product')),
            ],
            options={
                'verbose_name': 'Envase',
                'verbose_name_plural': 'Envases',
            },
        ),
        migrations.CreateModel(
            name='CompanyRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('funcion', models.CharField(blank=True, max_length=100)),
                ('razon_social', models.CharField(blank=True, max_length=300)),
                ('pais', models.CharField(blank=True, max_length=100)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_roles', to='registros.product')),
            ],
            options={
                'verbose_name': 'Función Empresa',
                'verbose_name_plural': 'Función Empresas',
            },
        ),
        migrations.CreateModel(
            name='ActiveIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_pa', models.CharField(blank=True, max_length=255)),
                ('concentracion', models.CharField(blank=True, max_length=50)),
                ('unidad_medida', models.CharField(blank=True, max_length=50)),
                ('parte', models.CharField(blank=True, max_length=100)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='formulas', to='registros.product')),
            ],
            options={
                'verbose_name': 'Fórmula (PA)',
                'verbose_name_plural': 'Fórmulas (PA)',
            },
        ),
    ]
