# Generated by Django 6.0.6 on 2026-06-17 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyrole',
            name='funcion_norm',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='companyrole',
            name='pais_norm',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='package',
            name='condicion_almacenamiento_norm',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='package',
            name='periodo_eficacia_norm',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
