# Generated by Django 6.0.6 on 2026-06-20 04:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0002_companyrole_funcion_norm_companyrole_pais_norm_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activeingredient',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='active_ingredients', to='registros.product'),
        ),
        migrations.AlterField(
            model_name='product',
            name='condicion_venta',
            field=models.CharField(blank=True, choices=[('Directa', 'Directa'), ('Receta Cheque', 'Receta Cheque'), ('Receta Retenida', 'Receta Retenida'), ('Receta Simple', 'Receta Simple'), ('Receta Retenida con Control de Existencia', 'Receta Retenida con Control de Existencia')], max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='equivalencia',
            field=models.CharField(blank=True, choices=[('Referente', 'Referente'), ('Equivalente Terapéutico', 'Equivalente Terapéutico'), ('Equivalente Terapéutico - Referente', 'Equivalente Terapéutico - Referente'), ('Biosimilar', 'Biosimilar'), ('Referente Biotecnológico', 'Referente Biotecnológico')], max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='estado',
            field=models.CharField(blank=True, choices=[('Vigente', 'Vigente'), ('No Vigente', 'No Vigente'), ('Vigente con suspensión voluntaria de distribución', 'Vigente con suspensión voluntaria de distribución')], max_length=100),
        ),
    ]
