# Generated by Django 6.0.6 on 2026-06-21 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0003_alter_activeingredient_producto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='control_legal',
            field=models.CharField(blank=True, choices=[('Psicotrópico', 'Psicotrópico'), ('Estupefaciente', 'Estupefaciente')], max_length=100),
        ),
    ]
