# Generated by Django 6.0.6 on 2026-06-24 03:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0005_alter_product_options_product_regimen_norm_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package',
            name='condicion_almacenamiento_norm',
        ),
    ]
