# Generated by Django 6.0.6 on 2026-06-25 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0006_remove_package_condicion_almacenamiento_norm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activeingredient',
            name='nombre_pa',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='package',
            name='descripcion',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='product',
            name='nombre',
            field=models.CharField(max_length=500),
        ),
    ]
