# Generated by Django 6.0.6 on 2026-06-25 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0007_widen_varchar_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activeingredient',
            name='parte',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
