# Generated by Django 6.0.6 on 2026-06-25 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0009_unaccent'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_checked_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Actualización de datos',
                'verbose_name_plural': 'Actualización de datos',
            },
        ),
    ]
